apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: demo-helm-chart
  namespace: flux-system
spec:
  spec:
  chart: ./chart/demo
  sourceRef:
    name: flux-system
    kind: GitRepository
  interval: 1m
  valuesFiles:
    - ./chart/demo/values.yaml
