apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  finalizers:
  - finalizers.fluxcd.io
  name: demo-helm-chart
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart/demo
      version: '1.0.x'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - ./chart/demo/values.yaml
  values:
    replicaCount: 2