apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  replicas:  {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        name: {{ .Values.app }}
        ports:
        - containerPort: {{ .Values.port }}
