env = "dev"
region = "us-east-1"
target_path = "/"
github_owner = "xerris"
repository_name = "2048-k8-app"
branch= "dev"
repo_provider =  "github"
default_components = ["source-controller", "kustomize-controller", "notification-controller"]
components = ["helm-controller"]