apiVersion: v1
kind: Service
metadata:
  name: "service-2048"
  namespace: "service-2048"
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: "2048-app"
